### ISSUE TITLE
Update existing test suite result when result already exists for a user

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/phpunit-test-reporter#1]
As a WP Unit Test Reporter user, I may want to re-run a build on a changeset that's already been reported. When I do so, it should update my existing report (instead of creating a new report).

**Comment by octalmage** [comment]
Hmm I'm not sure about this one. If something was fixed on the host, would it be useful at all to keep the historical results?

**Comment by danielbachhuber** [comment]
> If something was fixed on the host, would it be useful at all to keep the historical results?

I'd think it'd be fine to trigger a rebuild and have the rebuild replace the old results.

I'm more concerned with ending up with a bunch of duplicate reporting results when someone retries the same build over and over again.

**Comment by danielbachhuber** [comment]
Handled in #16
