### ISSUE TITLE
Support more than one testrunner from hosts.

### ISSUE THREAD

**Issue by getsource** [WordPress/phpunit-test-reporter#60]
It's been requested to have support for hosts to submit more than one environment that is being tested. This would be helpful for wider testing on more PHP configurations across hosting companies and environments.

At the moment, the only way for this to happen is for hosts to create a separate WordPress.org user and bot account for each environment, and be listed as a separate company for each one.

**Comment by Crixu** [comment]
This was done with the release of v0.2.0 released on 2024-09-17
