### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/phpunit-test-reporter#7]
@pento We're currently using the [Application Passwords](https://wordpress.org/plugins/application-passwords/) plugin to handle authentication. Do you want to use that on WordPress.org, or what alternative should we consider?

**Comment by pento** [comment]
I'm a little nervous about using https://github.com/georgestephanis/application-passwords. It's always been a bit of a low priority feature project, so hasn't received a lot of attention.

A code review would help, maybe @georgestephanis has thoughts on areas that he thinks need the most attention?

**Comment by danielbachhuber** [comment]
@pento Sorry, to clarify, when I mentioned code review I was referring to this specific plugin. I don't have a strong preference about authentication.

**Comment by danielbachhuber** [comment]
We're going to use the Application Passwords plugin, which @pento committed to WordPress.org and enabled on make/hosting
