### ISSUE TITLE
Hosting Team WCEU 2020 Video Intro

### ISSUE THREAD

**Issue by kittenkamala** [WordPress/phpunit-test-reporter#74]
The instructions are: 

"Choose an experienced contributor(s) from the team to record a short video introduction about your team. These videos will replace the traditional live introductions given during opening remarks and also used in the Contributor Day Orientation tool. Detailed guides for making these videos will be shared in the coming weeks."

The hosting team Reps will facilitate the making of this video, working with team member volunteers on every step.

**Comment by kittenkamala** [comment]
In the hosting meeting today (4/22/2020) I suggested that we: 

Team members record a quick 30 second clip saying "hello from [where you live]"  and then we can edit them all together with something brief from team reps at the beginning and end. So it'll be like: "hello from Bangladesh" .. "hello from Japan" .. "hello from the UK" ... "hello from Germany" .. "hello from the USA" etc and then "Hello from the Make WordPress Hosting Team! Welcome to the WCEU Contributor Day Hosting table! Thanks so much for joining " and so forth

The team brainstormed further: 

nullbyte  11:33 AM
@amykamala and maybe add something that everyone of you likes about hosting. For example:
"I like ngnix rewrite rules"
"I enjoy combing through logfiles"
...
To give your intro something hosting related quirky that people can relate (that also want to do hosting)
:face_with_hand_over_mouth:

amykamala:sunflower:  11:34 AM
Nice thinking! That would also make it feel a little more personal and human and tie the content back to hosting.

**Comment by getsource** [comment]
Noticed in the second update that it says these are due by May 8.

This has that, and what they'd like us to include:
https://make.wordpress.org/updates/2020/04/24/wceu-online-2020-contributor-day-update-times-registration-platforms-and-team-video-introductions/

I unfortunately don't have a lot of availability between now and then due to golden week, but happy to help with the time I do have.

**Comment by pfefferle** [comment]
is it possible to generate a hosting repo, so that we do not have to handle the hosting issues in the phpunit-* repos? Similar to https://github.com/indieweb/wiki for example

**Comment by kittenkamala** [comment]
@crixu has set up a cloud Virtual Machine to provide a space for hosting team members to upload their videos. Hosting Team members can contact @crixu, myself, @jadonn or @getsource for instructions on how to upload their video clip. This is being done on a one by one basis for security. 

@maze_held has offered to edit the video introduction for us. 

Thank you both! 

The WordPress brand and style guide is found here: https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/

Some general guidelines for WordCamp videos: 

https://make.wordpress.org/community/handbook/wordcamp-organizer/video/after-the-event-post-production/

https://make.wordpress.org/community/handbook/wordcamp-organizer/video/logos-in-wordcamp-videos/


**We are asking team members to please submit their clips by next Wednesday, May 6th.** 

More information on what is expected of the team can be found here: 

https://make.wordpress.org/updates/2020/04/24/wceu-online-2020-contributor-day-update-times-registration-platforms-and-team-video-introductions/

Our introduction will need to include: 
• who you are and which team you’re representing
• what the team does
• if there are any focuses during the WCEU 2020 Contributor Day
• how contributors can help your team
• any other relevant idea that you see fit for your team

In this case that relevant data is likely the php unit test runner and the improvements that have been in the works.

**Comment by jadonn** [comment]
According to https://make.wordpress.org/updates/2020/04/24/wceu-online-2020-contributor-day-update-times-registration-platforms-and-team-video-introductions/ the team introduction video should be no longer than 1 minute. It seems like we need to ask team members to record shorter introduction videos

**Comment by kittenkamala** [comment]
You are right - team members should make their video clips about 5 seconds.

**Comment by getsource** [comment]
> is it possible to generate a hosting repo (https://github.com/WordPress/hosting), so that we do not have to handle the hosting issues in the phpunit-* repos? Similar to https://github.com/indieweb/wiki for example

I agree it'd be better to have these somewhere other than the test repo, to avoid having team related items mixed with reporter bugs. Right now, I think the WordPress repos are all code related, rather that team management -- not sure if it has to stay that way or not.

**Comment by pfefferle** [comment]
Do you have an idea where to discuss this?

**Comment by pfefferle** [comment]
I think we can close this
