### ISSUE TITLE
Reach out to hosts to get reporting started again

### ISSUE THREAD

**Issue by getsource** [WordPress/phpunit-test-reporter#87]
As of this issue's creation, there are 13 hosts that are [not currently reporting tests](https://make.wordpress.org/hosting/test-results/).

This usually happens due to an error with the test runner on the environment (like a failed cron), or because tests have started to fail and were stopped.

It's definitely understandable to have failures, so this is meant as help, not as a problem!
That tests were ever reported is super appreciated.

Let's reach out to folks and see who we can help get going again.

Related: #61

**Comment by getsource** [comment]
We were chatting about this in the meeting today: https://wordpress.slack.com/archives/C3D6T7F8Q/p1602064418188500

I'll reach out to Bluehost and XSERVER.

**Comment by Crixu** [comment]
I'll reach out to WPWebHost and ZNetLive

**Comment by javiercasares** [comment]
I sent a few weeks ago an email to all the testers, so they should update and adapt their installations.

The latest version is compatible with, practically, anything ;)
