### ISSUE TITLE
Upgrade PHPUnit or Drop PHP 5.6 for TravisCI

### ISSUE THREAD

**Issue by getsource** [WordPress/phpunit-test-reporter#88]
Tests have [stopped passing](https://github.com/WordPress/phpunit-test-reporter/pull/84/checks?check_run_id=881824146) due to trunk requiring a newer version of PHPUnit.

We could upgrade, or change the way that tests are running, but it's worth noting that [make.wordpress.org runs PHP 7.2](https://wordpress.slack.com/archives/C02QB8GMM/p1596620196253000?thread_ts=1596619721.252700&cid=C02QB8GMM).

For this reason, I think it's okay to drop 5.6 to get tests passing again, but open to any options here.

**Comment by pfefferle** [comment]
fixed with #91
